scrape_configs:
  - job_name: 'cadvisor'

    # Override the global default and scrape targets from this job every 15 seconds.
    scrape_interval: 15s

    static_configs:
      - targets: [ 'cadvisor:8080' ]
