version: 2
registries:
  nuget-feed-default:
    type: nuget-feed
    url: https://api.nuget.org/v3/index.json

updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
    commit-message:
      prefix: "build"
    labels:
      - "type/build"
      - "scope/dockerfile"

  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    ignore:
    - dependency-name: "*Analyzers"
      versions:
      - ">= 0"
    registries:
    - nuget-feed-default
