services:
  app:
    build:
      context: .
    container_name: app
    environment:
      ## Uses Sqlite:
      # - ASPNETCORE_ENVIRONMENT=Development
      ## Uses MsSql server:
      - ASPNETCORE_ENVIRONMENT=Production
      # Override default port:
      - ASPNETCORE_HTTP_PORTS=8000
    ports:
      - 8000:8000
    depends_on:
      migrations:
        condition: service_completed_successfully

  # Run migrations:
  migrations:
    build: ./docker/migrations
    container_name: migrations
    tty: true
    environment:
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      ## Uses MsSql server:
      - ASPNETCORE_ENVIRONMENT=Production
    working_dir: /app
    volumes:
      - $PWD/src:/app:rw
      # Example of mounting appsettings.json and run migrations:
      #- $PWD/src/appsettings.json:/app/appsettings.json:ro
      #- $PWD/src/migrations:/app/migrations:rw
    entrypoint:
      - /bin/bash
      - -c
      - |
        set -exo pipefail
        dotnet ef database update --context ApplicationDbContext --verbose
        dotnet ef migrations list --no-build --context ApplicationDbContext --verbose
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db
    hostname: db
    environment:
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - ACCEPT_EULA=Y
      - MSSQL_AGENT_ENABLED=true
    ports:
      - 1433:1433
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "${MSSQL_SA_PASSWORD}" -Q "SELECT getdate()" -b
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
