name: staging
services:
  app:
    build:
      context: .
    image: ${IMAGE_REPO}:${RELEASE_VERSION:-latest}
    container_name: app
    restart: always
    develop:
      watch:
        - action: sync
          path: src
          target: /app
        - action: rebuild
          path: src
          target: /app
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTP_PORTS: "8080"
      MSSQL_SA_PASSWORD: Strong=Passw0rd
      VIRTUAL_PORT: "8080"
      ConnectionStrings__Default: Server=db;Initial Catalog=MudBlazorApp;UID=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=true;Connection Timeout=3;
    healthcheck:
      test:
        - CMD-SHELL
        - curl -sf -X 'GET' http://localhost:8080/healthz || exit 1
      timeout: 3s
      interval: 5s
      retries: 5
      start_period: 3s
    ports:
      - 8080:8080
    depends_on:
      migrations:
        condition: service_completed_successfully
        required: true

  migrations:
    image: ghcr.io/atrakic/mudblazor.migrations:latest
    restart: no
    tty: true
    container_name: migrations
    working_dir: /app
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__Default: Server=db;Initial Catalog=MudBlazorApp;UID=sa;Password=${MSSQL_SA_PASSWORD};TrustServerCertificate=true;Connection Timeout=3;
      MSSQL_SA_PASSWORD: Strong=Passw0rd
    volumes:
      - $PWD/src:/app:rw
    entrypoint:
      - /bin/bash
      - -c
      - |
        set -exo pipefail
        dotnet ef database update --context ApplicationDbContext --verbose
        dotnet ef migrations list --no-build --context ApplicationDbContext --verbose
    depends_on:
      db:
        condition: service_healthy
        required: true

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: no
    container_name: db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: "true"
      MSSQL_SA_PASSWORD: Strong=Passw0rd
    ports:
      - "1433:1433"
    hostname: db
    healthcheck:
      test:
        - CMD-SHELL
        - /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "Strong=Passw0rd" -Q "SELECT getdate()" -b
      timeout: 3s
      interval: 10s
      retries: 10
      start_period: 10s
