name: Playwright Tests
on:
  workflow_call:
    inputs:
      storeAdminUrl:
        required: true
        type: string
      storeFrontUrl:
        required: true
        type: string

jobs:
  playwright-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: npm
        cache-dependency-path: tests/package-lock.json
    - name: Install dependencies
      run: npm ci
      working-directory: tests/
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      working-directory: tests/
    - name: Run Playwright tests
      run: npx playwright test
      working-directory: tests/
      env:
        STORE_ADMIN_URL: ${{ inputs.storeAdminUrl }}
        STORE_FRONT_URL: ${{ inputs.storeFrontUrl }}
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report-store-admin
        path: tests/playwright-report/
        retention-days: 30
